#!/bin/bash
# teams has been declared as an associative array in the main shuriken script with declare -A teams


teams["ppp"]="10.0.1.1"
teams["Shellphish"]="10.0.2.1"
teams["Oops"]="10.0.3.1"
teams["fuzzi3"]="10.0.4.1"
teams["LCBC"]="10.0.5.1"
teams["Cykorkinsesis"]="10.0.6.1"
teams["spamandhex"]="10.0.7.1"
# teams["samurai"]="10.0.8.1"
teams["DragonSector"]="10.0.9.1"
teams["BlueLotus"]="10.0.10.1"
teams["shik"]="10.0.11.1"
teams["Bamboofox"]="10.0.12.1"
teams["YoykyWesterns"]="10.0.13.1"
